param(
    [string]$Distro = "Ubuntu"
)

$ErrorActionPreference = "Stop"

Write-Host "==> Building Zed for Windows (cargo build --release)"
# Build `cli` too: it produces target/release/cli.exe, used by the WSL `zed` shim
# below. `default-members` only includes the `zed` crate, so cli won't build otherwise.
cargo build --release --package zed --package cli
if ($LASTEXITCODE -ne 0) {
    Write-Error "Windows build failed (exit $LASTEXITCODE)"
}

$repoRoot = (Resolve-Path "$PSScriptRoot\..").Path
if ($repoRoot -notmatch '^([A-Za-z]):\\(.*)$') {
    Write-Error "Repo root '$repoRoot' is not a drive-letter path; cannot translate to WSL"
}
$repoWsl = "/mnt/$($Matches[1].ToLower())/$($Matches[2].Replace('\', '/'))"

Write-Host "==> Building remote_server in WSL ($Distro) at $repoWsl"

$bashScript = @'
set -e
cargo build --release --package remote_server --target-dir target/remote_server
mkdir -p ~/.zed_server
install -m 755 target/remote_server/release/remote_server ~/.zed_server/zed-remote-server-dev-build
echo "Installed: $(~/.zed_server/zed-remote-server-dev-build version 2>/dev/null || echo '?')"
'@

& wsl.exe -d $Distro --cd $repoWsl -- bash -c $bashScript
if ($LASTEXITCODE -ne 0) {
    Write-Error "WSL build failed (exit $LASTEXITCODE)"
}

# Install a `zed` shim into WSL's ~/.local/bin so that running `zed` inside WSL
# opens the current directory in this dev build (mirrors the release shim, which
# lives on the Windows PATH). ~/.local/bin precedes /mnt/c entries in WSL's PATH,
# so this overrides the release `zed`. The shim calls our dev cli.exe with --wsl,
# which translates the path via wslpath and connects to (or launches) the dev
# Zed.exe it finds next to cli.exe in target/release.
$cliWsl = "$repoWsl/target/release/cli.exe"
Write-Host "==> Installing WSL 'zed' shim -> $cliWsl"

# Generate the installer as a real file with LF endings and run it by path. We
# deliberately avoid `bash -c "<multiline>"`: PowerShell 5.1 mangles the quoting
# of complex arguments passed to native exes, and the heredoc body would be
# re-parsed by the login shell. The inner 'SHIM_EOF' heredoc is single-quoted so
# the shim's own $WSL_DISTRO_NAME / $USER are written literally, not expanded at
# install time.
$installerTemplate = @'
#!/usr/bin/env sh
set -e
mkdir -p ~/.local/bin
cat > ~/.local/bin/zed <<'SHIM_EOF'
#!/usr/bin/env sh
# Dev Zed launcher for WSL - generated by script/build-fork.ps1
CLI="__CLI_PATH__"
if [ -n "$WSL_DISTRO_NAME" ]; then
    WSL_USER="${USER:-$USERNAME}"
    exec "$CLI" --wsl "$WSL_USER@$WSL_DISTRO_NAME" "$@"
else
    exec "$CLI" "$@"
fi
SHIM_EOF
chmod +x ~/.local/bin/zed
echo "Installed dev 'zed' shim at ~/.local/bin/zed"
# This installer runs in a non-login shell, so its $PATH won't reflect the login
# shell. Treat ~/.local/bin as reachable if it's on PATH OR any rc file adds it.
on_path=no
case ":$PATH:" in *":$HOME/.local/bin:"*) on_path=yes ;; esac
if [ "$on_path" = no ] && grep -qs "local/bin" "$HOME/.zshrc" "$HOME/.zprofile" "$HOME/.profile" "$HOME/.bashrc"; then
    on_path=yes
fi
if [ "$on_path" = no ]; then
    echo "WARNING: ~/.local/bin is not on PATH. Add it to your shell rc to use 'zed'."
fi
'@

$installer = $installerTemplate.Replace('__CLI_PATH__', $cliWsl).Replace("`r`n", "`n")
$installerPath = Join-Path $repoRoot 'target\install-wsl-zed-shim.sh'
[IO.File]::WriteAllText($installerPath, $installer)

& wsl.exe -d $Distro -- bash "$repoWsl/target/install-wsl-zed-shim.sh"
if ($LASTEXITCODE -ne 0) {
    Write-Error "WSL shim install failed (exit $LASTEXITCODE)"
}

# Install a `zed` shim for Windows-native shells (PowerShell/cmd), mirroring the
# release installer which puts its bin dir on the Windows PATH. We drop a zed.cmd
# in a dedicated dir and prepend it to the user PATH so it overrides any installed
# release `zed`. Outside WSL the cli needs no --wsl flag; it resolves relative
# paths against the caller's cwd and detects the dev Zed.exe next to it.
$winCli = Join-Path $repoRoot "target\release\cli.exe"
$winShimDir = Join-Path $env:LOCALAPPDATA "zed-dev"
Write-Host "==> Installing Windows 'zed' shim -> $winCli"

New-Item -ItemType Directory -Force -Path $winShimDir | Out-Null
$zedCmd = @"
@echo off
"$winCli" %*
"@
# ASCII (no BOM) so cmd.exe doesn't choke on a leading byte-order mark.
Set-Content -Path (Join-Path $winShimDir "zed.cmd") -Value $zedCmd -Encoding ASCII

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$entries = if ($userPath) { $userPath -split ';' } else { @() }
if ($entries -notcontains $winShimDir) {
    $newPath = (@($winShimDir) + ($entries | Where-Object { $_ -ne "" })) -join ';'
    [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
    Write-Host "    Added $winShimDir to user PATH (restart shells to pick it up)."
} else {
    Write-Host "    $winShimDir already on user PATH."
}
